### ISSUE TITLE
build App Skeleton

### ISSUE THREAD

**Issue by alons-vayyar** [Vayyar/ChipProduction#1]
1. argsparse for parsing arguments (input file path, output file path, etc..)
1. function that parses the input file.
1. function implements the algorithm.
1. function that saves the outputs files.

**Comment by chaimchessrak-vayyar** [comment]
can I assume the following?
 wafers must be rectangles.
is the are only one wafer in a file.
garbage can't be on the same line with true content.

**Comment by alons-vayyar** [comment]
wafers must be rectangles. - **Yes (total wafer , include the dots(.))**
is the are only one wafer in a file. - **For now Yes.**
garbage can't be on the same line with true content.**-Yes**
